import Head from "next/head";
import { memo, useCallback, useEffect, useMemo, useRef, useState } from "react";

export default function Index() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>About</div>
    </>
  );
}
