import Head from "next/head";
import {
  Paper,
  Grid,
  Container,
  Box,
  Stack,
  Button,
  ThemeProvider,
} from "@mui/material";
import theme from "@/themes";
import { SignupForm } from "@/components/SignupForm";
import { LoginForm } from "@/components/LoginForm";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={theme}>
        <Container maxWidth="md">
          <SignupForm />
        </Container>
      </ThemeProvider>
    </>
  );
}
